name: dependency-check-action
on: 
  push:
    branches: [ master ]
  pull_request:
    types: [opened, reopened]

jobs:
  check-dependecys-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Run Tests
        run: yarn test:ci
       